services:
  # ChromaDB Vector Database
  chromadb:
    image: chromadb/chroma:latest
    container_name: chroma_vectordb
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    command: ["uvicorn", "chromadb.app:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: unless-stopped
    networks:
      - 911-network

  # Redis (cache)
  redis:
    image: redis:7-alpine
    container_name: evolution_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - 911-network

  # PostgreSQL (database)
  postgres:
    image: postgres:15-alpine
    container_name: evolution_postgres
    environment:
      POSTGRES_USER: evolution
      POSTGRES_PASSWORD: examplepassword
      POSTGRES_DB: evolution
    volumes:
      - evolution_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - 911-network

  # Evolution API
  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:v2.2.0
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - 911-network

  server:
    build: .
    container_name: server_911
    ports:
      - "8001:8000"
    environment:
      - EV_URL=http://evolution_api:8080
      - EV_API_KEY=${EV_API_KEY}
      - EV_INSTANCE=${EV_INSTANCE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - HOST=0.0.0.0
      - PORT=8000
      - LOG_LEVEL=info
    depends_on:
      - chromadb
      - evolution-api
    restart: unless-stopped
    networks:
      - 911-network

volumes:
  chroma_data:
  evolution_pgdata:
  evolution_instances:

networks:
  911-network:
    driver: bridge
