version: '3.8'

services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chroma_vectordb
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - CHROMA_HOST=0.0.0.0
      - CHROMA_PORT=8000
      - PERSIST_DIRECTORY=/chroma/chroma
    command: ["uvicorn", "chromadb.app:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: unless-stopped

volumes:
  chroma_data:
    driver: local 